<?php

require_once( dirname(__FILE__).'/base/baseauthmodulepool.php' );

/**
 * Autogenerated class AuthModulePool_Model
 *
 * @todo: documentation
 */
class AuthModulePool_Model extends BaseAuthModulePool_Model {
}
