<?php

require_once( dirname(__FILE__).'/base/baseauthmoduleset.php' );

/**
 * Autogenerated class AuthModuleSet_Model
 *
 * @todo: documentation
 */
class AuthModuleSet_Model extends BaseAuthModuleSet_Model {
	public function mayi_resource () {
		return "monitor.system.authmodules";
	}
}
