<?php

require_once( dirname(__FILE__).'/base/basepermissionquarkpool.php' );

/**
 * Autogenerated class PermissionQuarkPool_Model
 *
 * @todo: documentation
 */
class PermissionQuarkPool_Model extends BasePermissionQuarkPool_Model {
	/**
	 * Build a permission quark (int) from a type and a name.
	 *
	 * For each unique pair (type, name), a unique id is returned, such as
	 * Quark(type1,name1) == Quark(type2,name2) iff type1 == type2 and
	 * name1 == name2
	 *
	 * @param $type string
	 * @param $name string
	 * @return integer
	 */
	public static function build($type, $name) {
		$quark = static::all()
			->reduce_by('type', $type, '=')
			->reduce_by('name', $name, '=')
			->one();

		if(!$quark) {
			$quark = new PermissionQuark_Model();
			$quark->set_type($type);
			$quark->set_name($name);
			$quark->save();
		}

		return $quark->get_id();
	}
}
