<?php

require_once( dirname(__FILE__).'/base/baseusergroupset.php' );

/**
 * Autogenerated class UserGroupSet_Model
 *
 * @todo: documentation
 */
class UserGroupSet_Model extends BaseUserGroupSet_Model {
	public function mayi_resource () {
		return 'monitor.system.usergroups';
	}
}
