<?php

require_once( dirname(__FILE__).'/base/baseuserset.php' );

/**
 * Autogenerated class UserSet_Model
 *
 * @todo: documentation
 */
class UserSet_Model extends BaseUserSet_Model {

	public function mayi_resource () {
		return "monitor.system.users";
	}
}
