<?php

require_once( dirname(__FILE__).'/base/baseusergrouppool.php' );

/**
 * Autogenerated class UserGroupPool_Model
 *
 * @todo: documentation
 */
class UserGroupPool_Model extends BaseUserGroupPool_Model {
}
