<?php

require_once( dirname(__FILE__).'/base/basesavedqueries.php' );

/**
 * Autogenerated class SavedQueries_Model
 *
 * @todo: documentation
 */
class SavedQueries_Model extends BaseSavedQueries_Model {
}
