<?php

require_once( dirname(__FILE__).'/base/basesavedquery.php' );

/**
 * Autogenerated class SavedQuery_Model
 *
 * @todo: documentation
 */
class SavedQuery_Model extends BaseSavedQuery_Model {
	/**
	 * An array containing the custom column dependencies
	 */
	static public $rewrite_columns = array(
		'scope' => array('username')
	);

	/**
	 * Create an instance of the given type. Don't call dirctly, called from *Set_Model-objects
	 */
	public function __construct($values, $prefix) {
		parent::__construct($values, $prefix);
		$this->export[] = 'scope';
	}

	/**
	 * Get the scope as a string
	 */
	public function get_scope() {
		if( $this->get_username() === false ) {
			return 'global';
		}
		return 'user';
	}
}
