<?php

require_once( dirname(__FILE__).'/base/basesavedqueriespool.php' );

/**
 * Autogenerated class SavedQueriesPool_Model
 *
 * @todo: documentation
 */
class SavedQueriesPool_Model extends BaseSavedQueriesPool_Model {
}
