<?php

require_once( dirname(__FILE__).'/base/basesavedquery.php' );

/**
 * Autogenerated class SavedQuery_Model
 *
 * @todo: documentation
 */
class SavedQuery_Model extends BaseSavedQuery_Model {
	/**
	 * An array containing the custom column dependencies
	 */
	static public $rewrite_columns = array(
		'scope' => array('username'),
		'deletable' => array('username')
	);

	/**
	 * Create an instance of the given type. Don't call dirctly, called from *Set_Model-objects
	 */
	public function __construct($values, $prefix) {
		parent::__construct($values, $prefix);
		$this->export[] = 'scope';
		$this->export[] = 'deletable';
	}

	/**
	 * Get the scope as a string
	 */
	public function get_scope() {
		if( $this->get_username() === false ) {
			return 'global';
		}
		return 'user';
	}

	/**
	 * Get if current user is allowed to delete the object
	 */
	public function get_deletable() {
		switch( $this->get_scope() ) {
			case 'user': return true;
			case 'global': return op5auth::instance()->authorized_for('saved_queries_global');
		}
		return false;
	}
}
