<?php

require_once( dirname(__FILE__).'/base/basesavedquerypool.php' );

/**
 * Autogenerated class SavedQueryPool_Model
 *
 * @todo: documentation
 */
class SavedQueryPool_Model extends BaseSavedQueryPool_Model {
}
