<?php

require_once( dirname(__FILE__).'/base/basesavedreport.php' );

/**
 * Autogenerated class SavedReport_Model
 *
 * @todo: documentation
 */
class SavedReport_Model extends BaseSavedReport_Model {
}
