<?php

require_once( dirname(__FILE__).'/base/basesavedreportset.php' );

/**
 * Autogenerated class SavedReportSet_Model
 *
 * @todo: documentation
 */
class SavedReportSet_Model extends BaseSavedReportSet_Model {
	/**
	 * MayI reasource name
	 */
	public function mayi_resource() {
		return 'monitor.reports.saved_reports';
	}

	/**
	 * Filter out only reports allowed for the user.
	 *
	 * @todo: documentation
	 */
	protected function get_auth_filter() {
		$auth = op5auth::instance();
		$filter = new LivestatusFilterAnd();
		$filter->add( $this->filter );

		if (!$auth->authorized_for('host_view_all')) {
			$user = Auth::instance()->get_user()->username;
			$filter->add( new LivestatusFilterMatch( 'created_by', $user, '=' ) );
		}

		return $filter;
	}
}
