<?php

require_once( dirname(__FILE__).'/base/baserecurringdowntimepool.php' );

/**
 * Autogenerated class RecurringDowntimePool_Model
 *
 * @todo: documentation
 */
class RecurringDowntimePool_Model extends BaseRecurringDowntimePool_Model {
}
