<?php


/**
 * Autogenerated class Discovery_Hosts_Model
 *
 * @todo: documentation
 */
class Discovery_Hosts_Model extends BaseDiscovery_Hosts_Model {

	/**
	 * @ninja orm_command name Configure hosts
	 * @ninja orm_command category Operations
	 * @ninja orm_command icon shield-disabled
	 * @ninja orm_command mayi_method update.command.configure
	 * @ninja orm_command description
	 *     Configure host into Monitor
	 * @ninja orm_command view monitoring/naemon_command
	 */
	public function stop_event_handler() {
		return false;
	}


}
