<?php


/**
 * Autogenerated class Discovery_HostsSet_Model
 *
 * @todo: documentation
 */
class Discovery_HostsSet_Model extends BaseDiscovery_HostsSet_Model {
    public function mayi_resource () {
        return "monitor.monitoring.hosts";
    }
}
