<?php

require_once( dirname(__FILE__).'/base/basedashboard_widgetset.php' );

/**
 * Autogenerated class Dashboard_WidgetSet_Model
 *
 * @todo: documentation
 */
class Dashboard_WidgetSet_Model extends BaseDashboard_WidgetSet_Model {
}
