<?php

require_once( dirname(__FILE__).'/base/basedashboardpool.php' );

/**
 * Autogenerated class DashboardPool_Model
 *
 * @todo: documentation
 */
class DashboardPool_Model extends BaseDashboardPool_Model {
}
