<?php


/**
 * Autogenerated class Dashboard_Model
 *
 * @todo: documentation
 */
class Dashboard_Model extends BaseDashboard_Model
{
	/**
	 * Return the dashboard as an array, with widgets included
	 *
	 * @return array('dashboard' => ..., 'widgets' => ...);
	 */
	public function export_array()
	{
		$board = $this->export();
		/* we delete local-only variables */
		unset($board['id']);
		unset($board['username']);

		$ret = array('dashboard' => $board);

		$widget_set = $this->get_dashboard_widgets_set();

		$ret['widgets'] = array();
		foreach ($widget_set as $widget) {
			$w_ary = $widget->export();
			/* delete local-only variables */
			if (isset($w_ary['id'])) {
				unset($w_ary['id']);
			}
			if (isset($w_ary['dashboard'])) {
				unset($w_ary['dashboard']);
			}
			if (isset($w_ary['dashboard_id'])) {
				unset($w_ary['dashboard_id']);
			}
			$ret['widgets'][] = $w_ary;
		}

		return $ret;
	}

	/**
	 * Import an array to replace the current dashboard
	 *
	 * @return Nothing.
	 */
	public function import_array($ary)
	{
		$board_ary = $ary['dashboard'];
		$widgets_ary = $ary['widgets'];

		unset($board_ary['id']);
		foreach ($board_ary as $k => $v) {
			$mname = 'set_' . $k;
			if (!method_exists($this, $mname)) {
				continue;
			}
			$this->$mname($v);
		}
		$this->save();

		/*
		 * Delete widgets after save is successful.
		 * This should really only trigger for the "factory reset"
		 * case when someone replaces their existing dashboard,
		 * so performance isn't very important.
		 */
		foreach ($this->get_dashboard_widgets_set() as $wdg) {
			$wdg->delete();
		}

		foreach ($widgets_ary as $widget_ary) {
			unset($widget_ary['id']);
			$widget_ary['dashboard_id'] = $this->get_id();
			$widget = new Dashboard_Widget_Model();
			foreach ($widget_ary as $k => $v) {
				$mname = 'set_' . $k;
				if (!method_exists($widget, $mname)) {
					continue;
				}
				$widget->$mname($v);
			}
			$widget->save();
		}
	}

	/**
	 * Sets layout and converts to a new layout.
	 * @param $layout string The new layout.
	 */
	public function set_layout($layout) {
		if ($this->get_layout() === $layout) return;

		parent::set_layout($layout);

		// Only changes back and forth between layout 1,3,2 and 3,2,1.
		$widgets = $this->get_dashboard_widgets_set();
		foreach ($widgets as $w) {
			// $pos['c'] is the dashboard cell.
			// $pos['p'] is the position within the cell.
			$pos = $w->get_position();

			if ($layout === '1,3,2') { // 3,2,1 => 1,3,2
				$w->set_position(array(
					'c' => ($pos['c'] + 1) % 6,
					'p' => $pos['p']
				));
			} else { // 1,3,2 => 3,2,1
				$w->set_position(array(
					'c' => ($pos['c'] + 5) % 6,
					'p' => $pos['p']
				));
			}
			$w->save();
		}
	}

	/**
	 * Get if the user can write to the dashboard
	 *
	 * Since we only have access to private dashboards at the moment, we can always write to them.
	 *
	 * This is available since we plan to add sharable dashboards in the future.
	 */
	public function get_can_write() {
		return true;
	}
}
