<?php

require_once( dirname(__FILE__).'/base/basedashboard_widget.php' );

/**
 * Autogenerated class Dashboard_Widget_Model
 *
 * @todo: documentation
 */
class Dashboard_Widget_Model extends BaseDashboard_Widget_Model {
	/**
	 * For backward compatibility, get friendly name from widget
	 */
	public function get_friendly_name() {
		$metadata = $this->build()->get_metadata();
		if(isset($metadata['friendly_name']))
			return $metadata['friendly_name'];
		return 'Unknown';
	}

	/**
	 * Settings is stored as a json block in database, decode and encode
	 * @see BaseDashboard_Widget_Model::get_setting()
	 */
	public function get_setting() {
		$var = json_decode(parent::get_setting(), true);
		if(!is_array($var)) {
			return array();
		}
		return $var;
	}

	public function set_setting($value) {
		if (isset($value['title']) && strlen($value['title']) === 0)
			unset($value['title']);
		return parent::set_setting(json_encode($value, JSON_FORCE_OBJECT));
	}
}
