<?php

require_once( dirname(__FILE__).'/base/basedashboardset.php' );

/**
 * Autogenerated class DashboardSet_Model
 *
 * @todo: documentation
 */
class DashboardSet_Model extends BaseDashboardSet_Model {
}
