<?php

require_once( dirname(__FILE__).'/base/baseninja_widgetpool.php' );

/**
 * Autogenerated class NinjaWidgetPool_Model
 *
 * @todo: documentation
 */
class Ninja_WidgetPool_Model extends BaseNinja_WidgetPool_Model {
}
