<?php
/**
 * Nagios FIFO command helper
 *
 * @package    NINJA
 * @author     op5 AB
 * @license    GPL
 */
class nagioscmd_Core
{
	public function cmd_name($id = false, $name = false)
	{
		$cmd_name = array
		("NONE",

		 "ADD_HOST_COMMENT",
		 "DEL_HOST_COMMENT",

		 "ADD_SVC_COMMENT",
		 "DEL_SVC_COMMENT",

		 "ENABLE_SVC_CHECK",
		 "DISABLE_SVC_CHECK",

		 "SCHEDULE_SVC_CHECK",

		 "DELAY_SVC_NOTIFICATION",

		 "DELAY_HOST_NOTIFICATION",

		 "DISABLE_NOTIFICATIONS",
		 "ENABLE_NOTIFICATIONS",

		 "RESTART_PROCESS",
		 "SHUTDOWN_PROCESS",

		 "ENABLE_HOST_SVC_CHECKS",
		 "DISABLE_HOST_SVC_CHECKS",

		 "SCHEDULE_HOST_SVC_CHECKS",

		 "DELAY_HOST_SVC_NOTIFICATIONS",

		 "DEL_ALL_HOST_COMMENTS",
		 "DEL_ALL_SVC_COMMENTS",

		 "ENABLE_SVC_NOTIFICATIONS",
		 "DISABLE_SVC_NOTIFICATIONS",
		 "ENABLE_HOST_NOTIFICATIONS",
		 "DISABLE_HOST_NOTIFICATIONS",
		 "ENABLE_ALL_NOTIFICATIONS_BEYOND_HOST",
		 "DISABLE_ALL_NOTIFICATIONS_BEYOND_HOST",
		 "ENABLE_HOST_SVC_NOTIFICATIONS",
		 "DISABLE_HOST_SVC_NOTIFICATIONS",

		 "PROCESS_SERVICE_CHECK_RESULT",

		 "SAVE_STATE_INFORMATION",
		 "READ_STATE_INFORMATION",

		 "ACKNOWLEDGE_HOST_PROBLEM",
		 "ACKNOWLEDGE_SVC_PROBLEM",

		 "START_EXECUTING_SVC_CHECKS",
		 "STOP_EXECUTING_SVC_CHECKS",

		 "START_ACCEPTING_PASSIVE_SVC_CHECKS",
		 "STOP_ACCEPTING_PASSIVE_SVC_CHECKS",

		 "ENABLE_PASSIVE_SVC_CHECKS",
		 "DISABLE_PASSIVE_SVC_CHECKS",

		 "ENABLE_EVENT_HANDLERS",
		 "DISABLE_EVENT_HANDLERS",

		 "ENABLE_HOST_EVENT_HANDLER",
		 "DISABLE_HOST_EVENT_HANDLER",

		 "ENABLE_SVC_EVENT_HANDLER",
		 "DISABLE_SVC_EVENT_HANDLER",

		 "ENABLE_HOST_CHECK",
		 "DISABLE_HOST_CHECK",

		 "START_OBSESSING_OVER_SVC_CHECKS",
		 "STOP_OBSESSING_OVER_SVC_CHECKS",

		 "REMOVE_HOST_ACKNOWLEDGEMENT",
		 "REMOVE_SVC_ACKNOWLEDGEMENT",

		 "SCHEDULE_FORCED_HOST_SVC_CHECKS",
		 "SCHEDULE_FORCED_SVC_CHECK",

		 "SCHEDULE_HOST_DOWNTIME",
		 "SCHEDULE_SVC_DOWNTIME",

		 "ENABLE_HOST_FLAP_DETECTION",
		 "DISABLE_HOST_FLAP_DETECTION",

		 "ENABLE_SVC_FLAP_DETECTION",
		 "DISABLE_SVC_FLAP_DETECTION",

		 "ENABLE_FLAP_DETECTION",
		 "DISABLE_FLAP_DETECTION",

		 "ENABLE_HOSTGROUP_SVC_NOTIFICATIONS",
		 "DISABLE_HOSTGROUP_SVC_NOTIFICATIONS",

		 "ENABLE_HOSTGROUP_HOST_NOTIFICATIONS",
		 "DISABLE_HOSTGROUP_HOST_NOTIFICATIONS",

		 "ENABLE_HOSTGROUP_SVC_CHECKS",
		 "DISABLE_HOSTGROUP_SVC_CHECKS",

		 "CANCEL_HOST_DOWNTIME",
		 "CANCEL_SVC_DOWNTIME",

		 "CANCEL_ACTIVE_HOST_DOWNTIME",
		 "CANCEL_PENDING_HOST_DOWNTIME",

		 "CANCEL_ACTIVE_SVC_DOWNTIME",
		 "CANCEL_PENDING_SVC_DOWNTIME",

		 "CANCEL_ACTIVE_HOST_SVC_DOWNTIME",
		 "CANCEL_PENDING_HOST_SVC_DOWNTIME",

		 "FLUSH_PENDING_COMMANDS",

		 "DEL_HOST_DOWNTIME",
		 "DEL_SVC_DOWNTIME",

		 "ENABLE_FAILURE_PREDICTION",
		 "DISABLE_FAILURE_PREDICTION",

		 "ENABLE_PERFORMANCE_DATA",
		 "DISABLE_PERFORMANCE_DATA",

		 "SCHEDULE_HOSTGROUP_HOST_DOWNTIME",
		 "SCHEDULE_HOSTGROUP_SVC_DOWNTIME",
		 "SCHEDULE_HOST_SVC_DOWNTIME",

		 /* new commands in Nagios 2.x found below... */
		 "PROCESS_HOST_CHECK_RESULT",

		 "START_EXECUTING_HOST_CHECKS",
		 "STOP_EXECUTING_HOST_CHECKS",

		 "START_ACCEPTING_PASSIVE_HOST_CHECKS",
		 "STOP_ACCEPTING_PASSIVE_HOST_CHECKS",

		 "ENABLE_PASSIVE_HOST_CHECKS",
		 "DISABLE_PASSIVE_HOST_CHECKS",

		 "START_OBSESSING_OVER_HOST_CHECKS",
		 "STOP_OBSESSING_OVER_HOST_CHECKS",

		 "SCHEDULE_HOST_CHECK",
		 "SCHEDULE_FORCED_HOST_CHECK",

		 "START_OBSESSING_OVER_SVC",
		 "STOP_OBSESSING_OVER_SVC",

		 "START_OBSESSING_OVER_HOST",
		 "STOP_OBSESSING_OVER_HOST",

		 "ENABLE_HOSTGROUP_HOST_CHECKS",
		 "DISABLE_HOSTGROUP_HOST_CHECKS",

		 "ENABLE_HOSTGROUP_PASSIVE_SVC_CHECKS",
		 "DISABLE_HOSTGROUP_PASSIVE_SVC_CHECKS",

		 "ENABLE_HOSTGROUP_PASSIVE_HOST_CHECKS",
		 "DISABLE_HOSTGROUP_PASSIVE_HOST_CHECKS",

		 "ENABLE_SERVICEGROUP_SVC_NOTIFICATIONS",
		 "DISABLE_SERVICEGROUP_SVC_NOTIFICATIONS",

		 "ENABLE_SERVICEGROUP_HOST_NOTIFICATIONS",
		 "DISABLE_SERVICEGROUP_HOST_NOTIFICATIONS",

		 "ENABLE_SERVICEGROUP_SVC_CHECKS",
		 "DISABLE_SERVICEGROUP_SVC_CHECKS",

		 "ENABLE_SERVICEGROUP_HOST_CHECKS",
		 "DISABLE_SERVICEGROUP_HOST_CHECKS",

		 "ENABLE_SERVICEGROUP_PASSIVE_SVC_CHECKS",
		 "DISABLE_SERVICEGROUP_PASSIVE_SVC_CHECKS",

		 "ENABLE_SERVICEGROUP_PASSIVE_HOST_CHECKS",
		 "DISABLE_SERVICEGROUP_PASSIVE_HOST_CHECKS",

		 "SCHEDULE_SERVICEGROUP_HOST_DOWNTIME",
		 "SCHEDULE_SERVICEGROUP_SVC_DOWNTIME",

		 "CHANGE_GLOBAL_HOST_EVENT_HANDLER",
		 "CHANGE_GLOBAL_SVC_EVENT_HANDLER",

		 "CHANGE_HOST_EVENT_HANDLER",
		 "CHANGE_SVC_EVENT_HANDLER",

		 "CHANGE_HOST_CHECK_COMMAND",
		 "CHANGE_SVC_CHECK_COMMAND",

		 "CHANGE_NORMAL_HOST_CHECK_INTERVAL",
		 "CHANGE_NORMAL_SVC_CHECK_INTERVAL",
		 "CHANGE_RETRY_SVC_CHECK_INTERVAL",

		 "CHANGE_MAX_HOST_CHECK_ATTEMPTS",
		 "CHANGE_MAX_SVC_CHECK_ATTEMPTS",

		 "SCHEDULE_AND_PROPAGATE_TRIGGERED_HOST_DOWNTIME",

		 "ENABLE_HOST_AND_CHILD_NOTIFICATIONS",
		 "DISABLE_HOST_AND_CHILD_NOTIFICATIONS",

		 "SCHEDULE_AND_PROPAGATE_HOST_DOWNTIME",

		 "ENABLE_SERVICE_FRESHNESS_CHECKS",
		 "DISABLE_SERVICE_FRESHNESS_CHECKS",

		 "ENABLE_HOST_FRESHNESS_CHECKS",
		 "DISABLE_HOST_FRESHNESS_CHECKS",

		 "SET_HOST_NOTIFICATION_NUMBER",
		 "SET_SVC_NOTIFICATION_NUMBER",

		 /* new commands in Nagios 3.x found below... */
		 "CHANGE_HOST_CHECK_TIMEPERIOD",
		 "CHANGE_SVC_CHECK_TIMEPERIOD",

		 "PROCESS_FILE",

		 "CHANGE_CUSTOM_HOST_VAR",
		 "CHANGE_CUSTOM_SVC_VAR",
		 "CHANGE_CUSTOM_CONTACT_VAR",

		 "ENABLE_CONTACT_HOST_NOTIFICATIONS",
		 "DISABLE_CONTACT_HOST_NOTIFICATIONS",
		 "ENABLE_CONTACT_SVC_NOTIFICATIONS",
		 "DISABLE_CONTACT_SVC_NOTIFICATIONS",

		 "ENABLE_CONTACTGROUP_HOST_NOTIFICATIONS",
		 "DISABLE_CONTACTGROUP_HOST_NOTIFICATIONS",
		 "ENABLE_CONTACTGROUP_SVC_NOTIFICATIONS",
		 "DISABLE_CONTACTGROUP_SVC_NOTIFICATIONS",

		 "CHANGE_RETRY_HOST_CHECK_INTERVAL",

		 "SEND_CUSTOM_HOST_NOTIFICATION",
		 "SEND_CUSTOM_SVC_NOTIFICATION",

		 "CHANGE_HOST_NOTIFICATION_TIMEPERIOD",
		 "CHANGE_SVC_NOTIFICATION_TIMEPERIOD",
		 "CHANGE_CONTACT_HOST_NOTIFICATION_TIMEPERIOD",
		 "CHANGE_CONTACT_SVC_NOTIFICATION_TIMEPERIOD",

		 "CHANGE_HOST_MODATTR",
		 "CHANGE_SVC_MODATTR",
		 "CHANGE_CONTACT_MODATTR",
		 "CHANGE_CONTACT_MODHATTR",
		 "CHANGE_CONTACT_MODSATTR",

		 /* custom command introduced in Nagios 3.x */
		 999 => "CUSTOM_COMMAND");

		if (!empty($id)) {
			return $cmd_name[$id];
		}
		if (!empty($name)) {
			return array_search($name, $cmd_name);
		}
	}

	/**
	 * Obtain the command name for a command id
	 * @param $id The id of the command
	 * @return False on errors, the command name as a string on success
	 */
	public function command_name($id)
	{
		if ($id === false)
			return false;
		return self::cmd_name($id);
	}

	/**
	 * Obtain the id for a command
	 * @param $name The name of the command
	 * @return False on errors, the numeric id on success (may be 0)
	 */
	public function command_id($name)
	{
		if (empty($name))
			return false;

		$first = self::cmd_name(false, $name);
		if ($first !== false) {
			return $first;
		}

		# handle a CMD_ prefixed name too
		if (substr($name, 0, 4) === 'CMD_') {
			return self::cmd_name(false, substr($name, 4));
		}
		return false;
	}

	/**
	 * Obtain Nagios' macro name for the given command
	 * @param $id Numeric or string representation of command
	 * @return False on errors, Nagios' macro name as string on
	 */
	public function nagios_name($id)
	{
		if (is_numeric($id)) {
			$base_cmd = self::command_name($id);
			if (!$base_cmd) {
				return false;
			}
			return "CMD_" . $base_cmd;
		}
		if (self::command_id($name)) {
			return "CMD_" . $id;
		}
		return false;
	}

	public function submit_to_nagios($cmd, $pipe_path)
	{
		$fh = fopen($pipe_path, "w");
		if ($fh === false)
			return false;

		$len = fprintf($fh, "[%d] %s\n", time(), $cmd);
		fclose($fh);
		if (!$len)
			return false;

		return true;
	}
}
