#!/bin/bash

builddir=$1
if [ ! -d "$builddir" ]; then
	echo "I can not put my files in $builddir because it doesn't exist"
	exit 1
fi

prefix='/opt/monitor/op5/ninja'
AP2CONFDIR='/etc/opt/csw/apache2/extra'
gsed=/opt/csw/bin/gsed
PATH_DEF=`echo $PATH`
PATH=/usr/sbin:/usr/bin:/opt/csw/bin/:/opt/csw/gcc3/bin:/usr/ccs/bin

rm -rf $builddir
ninja_dir=$builddir$prefix
mkdir -p $ninja_dir

pushd cli-helpers
        make clean
        make
popd
make docs

# Whitelist instead of blacklist
cp -r Documentation \
Kohana_License.html \
NinjaPDO.inc.php \
README \
application \
cli-helpers \
docs \
example.htaccess \
generateKohanaDbFieldData.php \
geomap-thumb.png \
install_scripts \
modules \
op5-upgradescripts \
system \
index.php \
$ninja_dir

# The build script always looks for the op5build dir in the build root,
# to use it *for* packaging, not include it *in* the package.
cp -r op5build $builddir

$gsed -i \
        -e 's,^\(.config..site_domain.. = .\)/ninja/,\1/monitor/,' \
        -e 's/^\(.config..product_name.. = .\)Nagios/\1op5 Monitor/' \
        -e 's/^\(.config..show_cgi_links.. = .\)true/\1false/' \
        -e 's/^\(.config..version_info.. = .\)\/etc\/ninja-release/\1\/etc\/op5-monitor-release/' \
        $ninja_dir/application/config/config.php

$gsed -i -e "s/'IN_PRODUCTION', FALSE/'IN_PRODUCTION', TRUE/" $ninja_dir/index.php

# Used for the enterprise edition of Ninja
cp $builddir/op5build/login.png   $ninja_dir/application/views/themes/default/css/default/images
cp $builddir/op5build/favicon.ico $ninja_dir/application/views/themes/default/icons/16x16/
cp $builddir/op5build/icon.png $ninja_dir/application/views/themes/default/icons/

chmod -R a+r $ninja_dir

mkdir -p $builddir/etc/cron.d/
install -m 644 -c $builddir/etc/cron.d/ install_scripts/scheduled_reports.crontab
install -m 644 -c $builddir/etc/cron.d/ install_scripts/recurring_downtime.crontab

/opt/csw/bin/gsed -i -e 's/default\/cron/cron\/cron/' \
        $builddir/etc/cron.d/scheduled_reports.crontab
/opt/csw/bin/gsed -i -e 's/\/usr\/bin\/php/\/opt\/csw\/php5\/bin\/php/' \
        $builddir/etc/cron.d/scheduled_reports.crontab
/opt/csw/bin/gsed -i -e 's/\/usr\/bin\/php/\/opt\/csw\/php5\/bin\/php/' \
        $builddir/etc/cron.d/recurring_downtime.crontab
/opt/csw/bin/gsed -i -e 's/\/usr\/bin\/php/\/opt\/csw\/php5\/bin\/php/' \
        $builddir/opt/monitor/op5/ninja/application/controllers/default.php
/opt/csw/bin/gsed -i 's#tar tfz#/opt/csw/bin/gtar tfz#' $builddir/opt/monitor/op5/ninja/application/controllers/backup.php

# executables
for f in cli-helpers/apr_md5_validate install_scripts/ninja_db_init.sh;
do
	chmod 755 $ninja_dir/$f
done

# The custom_widgets dir need to be writable by the apache user
chmod 775 $ninja_dir/application/custom_widgets

mkdir -p $builddir/var/www/html
ln -sf $prefix $builddir/var/www/html/monitor
ln -sf $prefix $builddir/var/www/html/ninja

mkdir -p $builddir$AP2CONFDIR
cp $builddir/op5build/solaris/ninja.httpd-conf $builddir$AP2CONFDIR/ninja.conf


PATH=$PATH_DEF
