#!/bin/sh
prefix='/opt/monitor/op5/ninja'
AP2CONFDIR='/etc/opt/csw/apache2'
AP2_NINJA_CONF="/etc/opt/csw/apache2/extra/ninja.conf"

/usr/xpg4/bin/grep -q "Include $AP2_NINJA_CONF" $AP2CONFDIR/httpd.conf || echo "Include $AP2_NINJA_CONF" >> $AP2CONFDIR/httpd.conf

chown -R monitor:daemon /opt/monitor
chown -R monitor:daemon /var/www/

# svcadm restart  doesn't work, if service is not started
svcadm disable cswapache2
sleep 3
svcadm enable cswapache2

