<?php

require_once( dirname(__FILE__).'/base/basesavedfilterpool.php' );

/**
 * Autogenerated class SavedFilterPool_Model
 *
 * @todo: documentation
 */
class SavedFilterPool_Model extends BaseSavedFilterPool_Model {
}
