<?php

require_once( dirname(__FILE__).'/base/basesavedfilter.php' );

/**
 * Autogenerated class SavedFilter_Model
 *
 * @todo: documentation
 */
class SavedFilter_Model extends BaseSavedFilter_Model {
	/**
	 * An array containing the custom column dependencies
	 */
	static public $rewrite_columns = array(
		'scope' => array('username'),
		'deletable' => array('username')
	);

	/**
	 * Get the scope as a string
	 */
	public function get_scope() {
		if( $this->get_username() === false ) {
			return 'global';
		}
		return 'user';
	}

	/**
	 * Get if current user is allowed to delete the object
	 */
	public function get_deletable() {
		switch( $this->get_scope() ) {
			case 'user': return true;
			case 'global': return op5auth::instance()->authorized_for('saved_filters_global');
		}
		return false;
	}
}
