<?php

require_once( dirname(__FILE__).'/base/basesettingpool.php' );

/**
 * Autogenerated class SettingPool_Model
 *
 * @todo: documentation
 */
class SettingPool_Model extends BaseSettingPool_Model {
}
