<?php


/**
 * Autogenerated class SettingSet_Model
 *
 * @todo: documentation
 */
class SettingSet_Model extends BaseSettingSet_Model {
	public function mayi_resource () {
		return "monitor.system.settings";
	}
}
