<?php

require_once( dirname(__FILE__).'/base/basesettingset.php' );

/**
 * Autogenerated class SettingSet_Model
 *
 * @todo: documentation
 */
class SettingSet_Model extends BaseSettingSet_Model {
}
