post:
  install:
     - libyaml
  steps: |

    timedatectl set-timezone Europe/Stockholm
    if [ -f /etc/init.d/httpd ]; then service httpd restart; fi
    if [ -f /etc/init.d/mysqld ]; then service mysqld restart; fi

    if [ -f /usr/lib/systemd/system/httpd.service ]; then systemctl restart httpd; fi
    if [ -f /usr/lib/systemd/system/mariadb.service ]; then systemctl restart mariadb; fi

    mon restart

    # make sure deprecated code paths throw errors in our CI environment, MON-9199:
    echo 'deprecation_should_exit: 1' > /etc/op5/ninja.yml
    make -C /opt/monitor/op5/ninja test

    # Install Chrome, Ruby 2.7 and Ruby gems.
    # Runs the script in the current shell
    # Provided by op5int_webtest, current dir needs to be passed to the script.
    . /usr/bin/webtest.sh

    ulimit -c unlimited
    mkdir -p /mnt/logs
    echo "core ulimit: \$(ulimit -c)"
    export CUKE_SCREEN_DIR=/mnt/logs/screenshots
    #cucumber -t "not @unreliable" --strict --format html --out /mnt/logs/cucumber.html --format pretty --retry 2 --no-strict-flaky
    cucumber -t "@gian" -t "@gian_edited" --strict --format html --out /mnt/logs/cucumber.html --format pretty --retry 2 --no-strict-flaky

vm-config: |
    {"numCPUs": 4, "memoryMB": 8192}
