post:
  install:
     - libyaml
  steps: |

    if [ -f /etc/init.d/httpd ]; then service httpd restart; fi
    if [ -f /etc/init.d/mysqld ]; then service mysqld restart; fi

    if [ -f /usr/lib/systemd/system/httpd.service ]; then systemctl restart httpd; fi
    if [ -f /usr/lib/systemd/system/mariadb.service ]; then systemctl restart mariadb; fi

    mon restart

    # make sure deprecated code paths throw errors in our CI environment, MON-9199:
    echo 'deprecation_should_exit: 1' > /etc/op5/ninja.yml
    TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test

    # Install RVM to allow newer ruby versions
    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -sSL https://get.rvm.io | bash -s stable
    source /usr/local/rvm/scripts/rvm
    rvm install 2.5
    rvm use 2.5

    #Install chrome
    curl -OL https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    yum install -y google-chrome-stable_current_x86_64.rpm


    # Install cucumber and run tests
    gem install cucumber:3.2.0
    gem install capybara:3.18.0 --no-document
    gem install rspec:3.10.0 --no-document
    gem install parallel --no-document
    gem install parallel_tests --no-document
    gem install syntax:1.2.2 --no-document
    gem install cliver --no-document
    gem install webdrivers
    gem install selenium-webdriver
    gem install xpath

    ulimit -c unlimited
    mkdir -p /mnt/logs
    echo "core ulimit: \$(ulimit -c)"
    export CUKE_SCREEN_DIR=/mnt/logs/screenshots
    cucumber -t "not @unreliable" --strict --format html --out /mnt/logs/cucumber.html --format pretty

