post:
 install: ['npm']
 steps: |
  service httpd restart || service apache2 restart
  service mysqld restart || service mysql restart
  mon restart
  /opt/op5sys/lib/mock_license.php monitorHosts 500
  cp /var/op5license-tests/signed_valid/license.lic /etc/op5license/op5license.lic
  # make sure deprecated code paths throw errors in our CI environment, MON-9199:
  echo 'deprecation_should_exit: 1' > /etc/op5/ninja.yml
  npm install qunitjs -g --prefix /opt/monitor/op5/ninja/node_modules
  npm install node-qunit-phantomjs -g --prefix /opt/monitor/op5/ninja/node_modules
  TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test/qunit/test_suite.html
  TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test
