post:
 steps: |
  service httpd restart || service apache2 restart
  service mysqld restart || service mysql restart
  mon restart
  cp /var/op5license-tests/signed_valid/license.p7s /etc/op5license/op5license.p7s
  TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test
