post:
  install:
     - libyaml
  steps: |
    dnf update dnf
    dnf install -y dnf-plugins-core
    dnf module switch-to php:7.4

    # disable apc
    sed -i 's/opcache.enable=1/opcache.enable=0/g' /etc/php.d/10-opcache.ini
    sed -i 's/opcache.enable_cli=1/opcache.enable_cli=0/g' /etc/php.d/10-opcache.ini
    systemctl restart php-fpm

    if [ -f /etc/init.d/httpd ]; then service httpd restart; fi
    if [ -f /etc/init.d/mysqld ]; then service mysqld restart; fi

    if [ -f /usr/lib/systemd/system/httpd.service ]; then systemctl restart httpd; fi
    if [ -f /usr/lib/systemd/system/mariadb.service ]; then systemctl restart mariadb; fi

    mon restart

    # make sure deprecated code paths throw errors in our CI environment, MON-9199:
    echo 'deprecation_should_exit: 1' > /etc/op5/ninja.yml
    TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test

    # Install RVM to allow newer ruby versions
    gpg --import op5build/gpg_keys/*
    curl -sSL https://get.rvm.io | bash -s stable
    source /usr/local/rvm/scripts/rvm
    rvm install 2.7
    rvm use 2.7

    # Do not fail build on ruby warnings
    export RUBYOPT='-W:no-deprecated -W:no-experimental'

    #Install chrome
    curl -OL https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    yum install -y google-chrome-stable_current_x86_64.rpm


    # Install cucumber and run tests
    gem install cucumber:3.2.0
    gem install capybara:3.18.0 --no-document
    gem install rspec:3.10.0 --no-document
    gem install parallel --no-document
    gem install parallel_tests --no-document
    gem install syntax:1.2.2 --no-document
    gem install cliver --no-document
    gem install webdrivers
    gem install selenium-webdriver
    gem install puffing-billy --no-document
    gem install xpath

    ulimit -c unlimited
    mkdir -p /mnt/logs
    echo "core ulimit: \$(ulimit -c)"
    export CUKE_SCREEN_DIR=/mnt/logs/screenshots
    cucumber -t "not @unreliable" --strict --format html --out /mnt/logs/cucumber.html --format pretty --retry 2 --no-strict-flaky

vm-config: |
    {"numCPUs": 4, "memoryMB": 8192}
