post:
  install:
     - libyaml
  steps: |

    if [ -f /etc/init.d/httpd ]; then service httpd restart; fi
    if [ -f /etc/init.d/mysqld ]; then service mysqld restart; fi

    if [ -f /usr/lib/systemd/system/httpd.service ]; then systemctl restart httpd; fi
    if [ -f /usr/lib/systemd/system/mariadb.service ]; then systemctl restart mariadb; fi

    mon restart
    sed -i 's/Warn/Info/g' /etc/op5/lmd/lmd.ini
    if [ -f /usr/bin/systemctl ]; then
      systemctl start lmd
    else
      service lmd start
    fi

    # make sure deprecated code paths throw errors in our CI environment, MON-9199:
    echo 'deprecation_should_exit: 1' > /etc/op5/ninja.yml
    TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test

    # Install cucumber and run tests
    if [ -f /usr/bin/systemctl ]; then
      gem install cucumber:1.3.6 websocket-driver:0.7.0 nokogiri:1.6.0 rack:1.6.5 rack-test:0.7.0 capybara:2.1.0 public_suffix:2.0.5 xpath:2.0 rspec:2.14.1 parallel:1.13.0 parallel_tests:2.23.0 syntax:1.0.0 cliver:0.3.2 --no-document
      gem install poltergeist:1.11.0 -no-document --ignore-dependencies
    else
      gem2.0 install cucumber:1.3.6 websocket-driver:0.7.0 nokogiri:1.6.0 rack:1.6.5 rack-test:0.7.0 capybara:2.1.0 public_suffix:2.0.5 xpath:2.0 rspec:2.14.1 parallel:1.13.0 parallel_tests:2.23.0 syntax:1.0.0 cliver:0.3.2 --no-rdoc --no-ri
      gem2.0 install poltergeist:1.11.0 --no-rdoc --no-ri --ignore-dependencies
    fi

    ulimit -c unlimited
    mkdir -p /mnt/logs
    echo "core ulimit: \$(ulimit -c)"
    export CUKE_SCREEN_DIR=/mnt/logs/screenshots
    cucumber -t ~@skip -t ~@unreliable --strict --format html --out /mnt/logs/cucumber.html --format pretty
