post:
 steps: |
  service httpd restart || service apache2 restart
  service mysqld restart || service mysql restart
  mon restart
  TZ='Europe/Stockholm' make -C /opt/monitor/op5/ninja test
  make -C /opt/monitor/op5/ninja test-cucumber
