<?php

require_once( dirname(__FILE__).'/base/basefailingpool.php' );

/**
 * Autogenerated class FailingPool_Model
 *
 * @todo: documentation
 */
class FailingPool_Model extends BaseFailingPool_Model {
}
