<?php

require_once( dirname(__FILE__).'/base/basefailingset.php' );

/**
 * Autogenerated class FailingSet_Model
 *
 * @todo: documentation
 */
class FailingSet_Model extends BaseFailingSet_Model {
	/**
	 * Return resource name of this object
	 * @return string
	 */
	public function mayi_resource() {
		return "ninja.test.failing";
	}
}
