<?php


/**
 * Autogenerated class TestClassBSet_Model
 *
 * @todo: documentation
 */
class TestClassBSet_Model extends BaseTestClassBSet_Model {
	public function mayi_resource () {
		return "ninja.test.class.b";
	}
}
