<?php


/**
 * Autogenerated class TestClassASet_Model
 *
 * @todo: documentation
 */
class TestClassASet_Model extends BaseTestClassASet_Model {
	public function mayi_resource () {
		return "ninja.test.class.a";
	}
}
